create database FINANCEIRO;

USE FINANCEIRO;
GO

--CRIANDO TABELAS

CREATE TABLE CATEGORIA (
   ID_CATEGORIA INT PRIMARY KEY NOT NULL IDENTITY,
   NOME VARCHAR(50) NOT NULL,
   LIMITE MONEY NOT NULL
);

CREATE TABLE MOVIMENTO (
  ID_MOVIMENTO INT PRIMARY KEY NOT NULL IDENTITY,
  DESCRICAO VARCHAR(50) NOT NULL,
  VALOR MONEY NOT NULL,
  DATA_CADASTRO DATE NOT NULL,
  ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(ID_CATEGORIA) 
);

select * from movimento;
go



